version: 0.2

phases:
  install:
    runtime-versions:
      dotnet: 8.0
  build:
    commands:
      - echo "Restoring..."
      - dotnet restore
      - echo "Building..."
      - dotnet build -c Release
      - echo "Publishing..."
      - dotnet publish -c Release -o publish
artifacts:
  files:
    - '**/*'
  base-directory: publish
